[IMAGE_CONFIGURATION]

# Abilita o disabilita la fase di conversione dei file PE in immagini
# 1 -> esegue la conversione
# 0 -> salta questa fase
enabled = 1

# Path della cartella che contiene i file PE Windows da convertire
filesPath = /kaggle/input/datasets/domenicobianchini/pe-malware-dataset/test/samples

# Path del file CSV che contiene le label dei file PE
labelsPath = /kaggle/input/datasets/domenicobianchini/pe-malware-dataset/test/labels.csv

# Path della cartella in cui salvare le immagini generate
imagesPath = /kaggle/working/images/test

# Path del file CSV da creare contenente il mapping tra il path delle immagini generate e le relative label
imageLabelsPath = /kaggle/working/images/test/image_labels.csv

# Strategia di mapping da utilizzare per costruire l'immagine
# Valori possibili:
# LINEAR | ZIGZAG | SERPENTINE
mappingType = LINEAR

# Larghezza dell'immagine
width = 224

# Altezza dell'immagine
# Se valorizzata -> modalità FIXED
# Se lasciata a 0 -> modalità VARIABLE
height = 224

# Numero di canali dell'immagine
# 1 -> grayscale (1 byte per pixel)
# 3 -> RGB (3 byte per pixel)
numberOfChannels = 3

# Larghezza per il resize delle immagini
resizeWidth = 0

# Altezza per il resize delle immagini
resizeHeight = 0

[TRAIN_CONFIGURATION]

# Abilita o disabilita la fase di training
# 1 -> esegue il training
# 0 -> salta questa fase
enabled = 0

# Path del file CSV contenente il mapping immagini-label per il training
imageLabelsPath = dataset/train/image_labels.csv

# Numero di epoche
epochs = 10

# Learning rate
learningRate = 0.001

# Path dove salvare il modello migliore
modelPath = best_models

[TEST_CONFIGURATION]

# Abilita o disabilita la fase di test
# 1 -> esegue il test
# 0 -> salta questa fase
enabled = 0

# Path del file CSV contenente il mapping immagini-label
imageLabelsPath = dataset/test/image_labels.csv

# Path del modello da utilizzare per il test
modelPath = best_models/LINEAR_224x224_RGB

# Path del file CSV dove salvare i risultati delle metriche del test
resultsPath = results/classification_metrics.csv