[IMAGE_CONFIGURATION]

# Abilita o disabilita la fase di conversione dei file PE in immagini
# 1 -> esegue la conversione
# 0 -> salta questa fase
enabled = 0

# Path della cartella che contiene i file PE Windows da convertire
filesPath = dataset/samples

# Path del file CSV che contiene le label dei file PE
labelsPath = dataset/samples.csv

# Path della cartella in cui salvare le immagini generate
imagesPath = images

# Path del file CSV contenente il mapping tra il path delle immagini generate e le relative label
imageMapping = dataset/imageMapping.csv

# Strategia di mapping da utilizzare per costruire l'immagine
# Valori possibili:
# LINEAR | ZIGZAG | SERPENTINE
mappingType = LINEAR

# Larghezza dell'immagine
width = 224

# Altezza dell'immagine
# Se valorizzata -> modalità FIXED
# Se lasciata a 0 -> modalità VARIABLE
height = 224

# Numero di canali dell'immagine
# 1 -> grayscale (1 byte per pixel)
# 3 -> RGB (3 byte per pixel)
numberOfChannels = 3

[TRAIN_CONFIGURATION]

# Abilita o disabilita la fase di training
# 1 -> costruisce Dataset, DataLoader ed esegue la ResNet
# 0 -> salta questa fase
enabled = 1

# Larghezza target per il resize
resizeWidth = 0

# Altezza target per il resize
resizeHeight = 0