[IMAGE_CONFIGURATION]

# Path della cartella che contiene i file PE Windows da convertire
filesPath = dataset

# Strategia di mapping da utilizzare per costruire l'immagine
# Valori possibili:
# LINEAR | ZIGZAG | SERPENTINE
mappingType = LINEAR

# Larghezza dell'immagine
width = 256

# Altezza dell'immagine
# Se valorizzata -> modalita FIXED
# Se lasciata vuota -> modalita VARIABLE
height = 256

# Numero di canali dell'immagine
# 1 -> grayscale (1 byte per pixel)
# 3 -> RGB (3 byte per pixel)
numberOfChannels = 1