[DATASET]

# Path della cartella che contiene le immagini generate dai file PE
imagesPath=images

# Path del file CSV che contiene le label associate alle immagini generate
labelsPath=dataset/labels.csv